[project]
name = "secureeye"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=6.20.0",
    "numpy==1.26.4",
    "openai>=2.48.0",
    "pillow>=12.3.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.2",
    "pywebview>=6.2.1",
    "xlsxwriter>=3.2.9",
]
